# fly.toml app configuration file generated for typesense-pkgs-ml on 2024-04-25T23:09:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'typesense-pkgs-ml'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8108
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
